### ISSUE TITLE
use vitest for test

### ISSUE THREAD

**Issue by konpeki622** [originjs/origin.js#119]
### Is your feature request related to a problem? Please describe.

Origin.js creates server with vite, which means we can get faster testing and more simple configuration if using vitest.

### Describe the solution you'd like

- options to select jest or vitest for test in an Origin.js project.
- migrate package testing to vitest

**Comment by konpeki622** [comment]
I met some problem when migrating jest mock modules in `cli-service` package and it related to this [issue](https://github.com/vitest-dev/vitest/issues/111).

**Comment by sheremet-va** [comment]
This was fixed in the latest release
