### ISSUE TITLE
Publish the TypeScript typings for vite-plugin-content

### ISSUE THREAD

**Issue by pedrolamas** [originjs/origin.js#172]
### Is your feature request related to a problem? Please describe.

I can see that vite--plugin-content is completely written in TypeScript, yet the typings are missing on the npm package.

It would be really nice (and easy!) to get these published in the package so that consumer projects can get proper typing help while writing the code!

![image](https://user-images.githubusercontent.com/85504/208697192-31bdf62c-8ef4-429b-9f27-2ccbda0e6c4e.png)

### Describe the solution you'd like

Output and publish the TypeScript typings in the npm package.

### Describe alternatives you've considered

Ignoring the error.

### Additional context

(None)

**Comment by PeterAlfredLee** [comment]
Hi @pedrolamas 
Thanks for your suggestion. :)
I just published a new version `1.0.2`, which contains .d.ts types. Could you have a try?

**Comment by pedrolamas** [comment]
Thank you @PeterAlfredLee, I have just checked version 1.0.2 and it is indeed providing the TypeScript types!
