### ISSUE TITLE
MJS build for content-plugin doesn't work in 1.0.2 due to using require

### ISSUE THREAD

**Issue by kalvenschraut** [originjs/origin.js#181]
![image](https://github.com/originjs/origin.js/assets/30308012/b3d7c7e9-5f91-4941-9d4c-2f679a6f08e6)
Require isn't defined in a mjs file, have to use dynamic import to lazily load these things. Or do a createRequire https://nodejs.org/api/module.html#modulecreaterequirefilename

https://github.com/originjs/origin.js/blob/main/packages/vite-plugin-content/src/index.ts#L105

**Comment by PeterAlfredLee** [comment]
Hi @kalvenschraut 
I'm not that familiar with mjs. Seems `require` is not valid in your case. Could you provide more detailed information about your environment? Like version of nodejs?

Besides, a PR is always welcome.

**Comment by kalvenschraut** [comment]
This would be an issue with any nodejs version above 16 I believe.

Basically if using ESM modules, require is not defined in nodejs. Either you have to use that create require function I linked above to specifically use require, or change all of your static requires to be dynamic imports.

Actually looking at the code it should be trivial to change them to dynamic imports. Will submit a PR.

**Comment by kalvenschraut** [comment]
Also to note that dynamic import should work just fine for CJS files (require) syntax.

**Comment by HexaCubist** [comment]
I believe this issue might need to be reopened - require is still used here and breaks XLSX transformation: https://github.com/originjs/origin.js/blob/main/packages/vite-plugin-content/src/xlsxTransformation.ts
