### ISSUE TITLE
[vite-plugin-content] Upgrade deps for security

### ISSUE THREAD

**Issue by pcorpet** [originjs/origin.js#196]
### Versions

- originjs: v1.0.4
- node: v20.4.0

### Reproduction

The current version of the package has 2 vulnerable dependencies:
- xlsx (currently `^0.17.1`): https://github.com/advisories/GHSA-4r6h-8v6p-xvw6
- xml2js (currently released `^0.4.23`): https://github.com/advisories/GHSA-776f-qx25-q3cc

I see that you have bumped the xml2js dep in 3961275bbe6190f694d32169da9316a4891283d6, however xlsx is still old, and we would like a release to NPM if possible.

**Comment by PeterAlfredLee** [comment]
Hi @pcorpet Thanks for your report.
I will make a release these days.

**Comment by PeterAlfredLee** [comment]
Just published `1.0.5`. Hope it helps.

**Comment by pcorpet** [comment]
Thanks a lot!
