### ISSUE TITLE
Cannot find module '@rollup/pluginutils'

### ISSUE THREAD

**Issue by nicooprat** [originjs/origin.js#59]
Just tried your plugin, got this error:

```
[vite] Internal server error: Cannot find module '@rollup/pluginutils'
```

Looks like `npm i -D @rollup/pluginutils` fixed it, but I think this dep should be listed in your `dependencies` or `peerDependencies` instead?

https://github.com/originjs/origin.js/blob/dd54ef18309f083c3243f4d9525c2a1d83626d1f/packages/vite-plugin-content/src/yamlTransformation.ts#L3

Thanks for your work anyway!

**Comment by PeterAlfredLee** [comment]
Hi @nicooprat 
Thank you for your reporting.
I mistakenly put this into devDependencies.
I just pushed a new version. Could you have a look again?

**Comment by nicooprat** [comment]
It’s working, thanks!
